version: 2

models:
  - name: fact_complaints
    description: "The core fact table containing all complaints."
    columns:
      - name: ticket_id
        tests:
          - unique
          - not_null
          
      - name: district_th
        tests:
          - not_null
          - relationships:
              to: ref('dim_districts')
              field: district_th

  - name: dim_districts
    columns:
      - name: district_th
        tests:
          - unique
          - not_null
